- name: Install OS nginx package
  apt:
    name: nginx
    state: latest
  when:
    ansible_os_family == "Debian"
  tags: nginx

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: nginx             

- name: Start nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
  tags: nginx

- name: Make sure 'nginx' is started
  systemd:
    name: nginx
    state: started
    enabled: true
  register: result
  tags: nginx

- name: Show result
  debug:
    msg: "{{ result }}"
  tags: nginx
